import { Contacto as Contact } from '../../types/contactos';

export const fakeContacts: Contact[] = [
  {
    id: '1',
    primerNombre: 'María',
    apellido: 'González',
    telefonoPrincipal: '+505 8212 3344',
    telefonoSecundario: '+505 7612 1144',
    correoElectronico: 'maria.gonzalez@example.com',
    direccion: 'Calle Principal #123',
    ciudad: 'Managua',
    estado: 'Managua',
    codigoPostal: '14002',
    pais: 'Nicaragua',
    fechaCreacion: '2023-01-01',
    fechaActualizacion: '2023-03-15',
    estaActivo: true,
    tipoContacto: 'cliente',
  },
  {
    id: '2',
    primerNombre: 'Carlos',
    apellido: 'Ramírez',
    telefonoPrincipal: '+507 6988 4455',
    telefonoSecundario: '+507 6122 3344',
    correoElectronico: 'carlos.ramirez@example.com',
    direccion: 'Av. Central Edif. Alfa, Piso 5',
    ciudad: 'Panamá',
    estado: 'Panamá',
    codigoPostal: '0801',
    pais: 'Panamá',
    fechaCreacion: '2023-01-12',
    fechaActualizacion: '2023-04-01',
    estaActivo: true,
    tipoContacto: 'proveedor',
  },
  {
    id: '3',
    primerNombre: 'Fernanda',
    apellido: 'Torres',
    telefonoPrincipal: '+52 442 123 4567',
    telefonoSecundario: '+52 442 765 4321',
    correoElectronico: 'fernanda.torres@example.com',
    direccion: 'Calle 5 de Mayo #85, Centro Histórico',
    ciudad: 'Querétaro',
    estado: 'Querétaro',
    codigoPostal: '76000',
    pais: 'México',
    fechaCreacion: '2022-12-20',
    fechaActualizacion: '2023-01-15',
    estaActivo: false,
    tipoContacto: 'otro',
  },
  {
    id: '4',
    primerNombre: 'Luis',
    apellido: 'Martínez',
    telefonoPrincipal: '+56 9 7654 3210',
    telefonoSecundario: '+56 9 1234 5678',
    correoElectronico: 'luis.martinez@example.com',
    direccion: 'Av. Los Leones 203, Providencia',
    ciudad: 'Santiago',
    estado: 'Región Metropolitana',
    codigoPostal: '8320000',
    pais: 'Chile',
    fechaCreacion: '2023-02-05',
    fechaActualizacion: '2023-05-22',
    estaActivo: true,
    tipoContacto: 'cliente',
  },
  {
    id: '5',
    primerNombre: 'Valentina',
    apellido: 'Pérez',
    telefonoPrincipal: '+57 312 345 6789',
    telefonoSecundario: '+57 310 112 2334',
    correoElectronico: 'valentina.perez@example.com',
    direccion: 'Carrera 45 #18-25, El Poblado',
    ciudad: 'Medellín',
    estado: 'Antioquia',
    codigoPostal: '050021',
    pais: 'Colombia',
    fechaCreacion: '2023-01-30',
    fechaActualizacion: '2023-03-08',
    estaActivo: true,
    tipoContacto: 'proveedor',
  },
  {
    id: '6',
    primerNombre: 'Javier',
    apellido: 'López',
    telefonoPrincipal: '+54 911 6789 1234',
    telefonoSecundario: '+54 911 3344 5566',
    correoElectronico: 'javier.lopez@example.com',
    direccion: 'Calle Corrientes 1234, Piso 2',
    ciudad: 'Buenos Aires',
    estado: 'Buenos Aires',
    codigoPostal: 'C1001',
    pais: 'Argentina',
    fechaCreacion: '2022-11-11',
    fechaActualizacion: '2023-01-09',
    estaActivo: false,
    tipoContacto: 'otro',
  },
  {
    id: '7',
    primerNombre: 'Camila',
    apellido: 'Reyes',
    telefonoPrincipal: '+503 7788 9900',
    telefonoSecundario: '+503 6600 1122',
    correoElectronico: 'camila.reyes@example.com',
    direccion: 'Av. Las Palmas 32, Colonia Escalón',
    ciudad: 'San Salvador',
    estado: 'San Salvador',
    codigoPostal: '01101',
    pais: 'El Salvador',
    fechaCreacion: '2023-03-01',
    fechaActualizacion: '2023-03-15',
    estaActivo: true,
    tipoContacto: 'cliente',
  },
  {
    id: '8',
    primerNombre: 'Mateo',
    apellido: 'Fernández',
    telefonoPrincipal: '+506 8899 7766',
    telefonoSecundario: '+506 2222 3333',
    correoElectronico: 'mateo.fernandez@example.com',
    direccion: 'Calle El Sol 50, Barrio Escalante',
    ciudad: 'San José',
    estado: 'San José',
    codigoPostal: '10101',
    pais: 'Costa Rica',
    fechaCreacion: '2023-02-20',
    fechaActualizacion: '2023-04-02',
    estaActivo: true,
    tipoContacto: 'proveedor',
  },
  {
    id: '9',
    primerNombre: 'Isabella',
    apellido: 'Morales',
    telefonoPrincipal: '+58 412 345 6789',
    telefonoSecundario: '+58 414 123 4567',
    correoElectronico: 'isabella.morales@example.com',
    direccion: 'Av. Bolívar Norte, Torre Zulia',
    ciudad: 'Valencia',
    estado: 'Carabobo',
    codigoPostal: '2001',
    pais: 'Venezuela',
    fechaCreacion: '2023-01-18',
    fechaActualizacion: '2023-02-01',
    estaActivo: false,
    tipoContacto: 'otro',
  },
  {
    id: '10',
    primerNombre: 'Diego',
    apellido: 'Rojas',
    telefonoPrincipal: '+51 989 123 456',
    telefonoSecundario: '+51 988 654 321',
    correoElectronico: 'diego.rojas@example.com',
    direccion: 'Jr. Los Olivos 154, San Borja',
    ciudad: 'Lima',
    estado: 'Lima',
    codigoPostal: '15082',
    pais: 'Perú',
    fechaCreacion: '2023-02-10',
    fechaActualizacion: '2023-05-01',
    estaActivo: true,
    tipoContacto: 'cliente',
  },
];
