import { Tarea as Task } from '../../types/tareas';

export const fakeTasks: Task[] = [
  {
    id: '1',
    titulo: 'Tarea 1',
    descripcion: 'Descripción de la tarea 1',
    estado: 'pendiente',
    asignadoA: 'Usuario 1',
    creadoPor: 'Usuario 1',
    estaActiva: true,
    fechaCreacion: '2023-01-01',
    fechaActualizacion: '2023-01-01',
  },
  {
    id: '2',
    titulo: 'Tarea 2',
    descripcion: 'Descripción de la tarea 2',
    estado: 'en_progreso',
    asignadoA: 'Usuario 2',
    creadoPor: 'Usuario 2',
    estaActiva: true,
    fechaCreacion: '2023-01-02',
    fechaActualizacion: '2023-01-02',
  },
  {
    id: '3',
    titulo: 'Redactar informe mensual',
    descripcion: 'Compilar datos y redactar informe para la gerencia.',
    estado: 'completada',
    asignadoA: 'Ana López',
    creadoPor: 'Carlos Ruiz',
    estaActiva: false,
    fechaCreacion: '2023-01-05',
    fechaActualizacion: '2023-01-10',
  },
  {
    id: '4',
    titulo: 'Diseñar logotipo nuevo',
    descripcion: 'Crear un logotipo moderno para la marca.',
    estado: 'pendiente',
    asignadoA: 'Luis García',
    creadoPor: 'María Pérez',
    estaActiva: true,
    fechaCreacion: '2023-01-06',
    fechaActualizacion: '2023-01-06',
  },
  {
    id: '5',
    titulo: 'Actualizar sitio web',
    descripcion: 'Subir nuevas imágenes y optimizar rendimiento.',
    estado: 'en_progreso',
    asignadoA: 'Carlos Martínez',
    creadoPor: 'Ana López',
    estaActiva: true,
    fechaCreacion: '2023-01-07',
    fechaActualizacion: '2023-01-09',
  },
  {
    id: '6',
    titulo: 'Revisión del presupuesto',
    descripcion: 'Analizar gastos del último trimestre.',
    estado: 'completada',
    asignadoA: 'Fernando Torres',
    creadoPor: 'Luis García',
    estaActiva: false,
    fechaCreacion: '2023-01-08',
    fechaActualizacion: '2023-01-15',
  },
  {
    id: '7',
    titulo: 'Reunión con proveedores',
    descripcion: 'Planificar reunión para renegociar términos.',
    estado: 'pendiente',
    asignadoA: 'María Pérez',
    creadoPor: 'Carlos Ruiz',
    estaActiva: true,
    fechaCreacion: '2023-01-09',
    fechaActualizacion: '2023-01-09',
  },
  {
    id: '8',
    titulo: 'Campaña publicitaria',
    descripcion: 'Planificación y diseño de campaña para redes sociales.',
    estado: 'en_progreso',
    asignadoA: 'Ana López',
    creadoPor: 'Carlos Martínez',
    estaActiva: true,
    fechaCreacion: '2023-01-10',
    fechaActualizacion: '2023-01-11',
  },
  {
    id: '9',
    titulo: 'Capacitación empleados',
    descripcion: 'Organizar taller de bienvenida para nuevos ingresos.',
    estado: 'pendiente',
    asignadoA: 'Fernando Torres',
    creadoPor: 'Luis García',
    estaActiva: true,
    fechaCreacion: '2023-01-12',
    fechaActualizacion: '2023-01-12',
  },
  {
    id: '10',
    titulo: 'Presentación a clientes',
    descripcion: 'Preparar presentación visual e informativa.',
    estado: 'completada',
    asignadoA: 'Carlos Ruiz',
    creadoPor: 'María Pérez',
    estaActiva: false,
    fechaCreacion: '2023-01-13',
    fechaActualizacion: '2023-01-14',
  },
];
