services:
  redis:
    image: redis:latest
    container_name: redis_user_session
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  keycloak-db:
    image: postgres:15
    container_name: keycloak_db
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.1
    container_name: keycloak
    restart: always
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: mysecretpassword
      KC_HOSTNAME_STRICT: "false"
    ports:
      - "8082:8080"
    depends_on:
      keycloak-db:
        condition: service_healthy
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./CoreUnityBackend/keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json

  identity_db:
    build:
      context: ./CoreUnityBackend/docker_db/identity-db
    container_name: identity_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5434:5432"
    volumes:
      - identity_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  coreunity.webapi:
    image: coreunitywebapi
    build:
      context: ./CoreUnityBackend
      dockerfile: CoreUnity.WebAPI/Dockerfile
    container_name: core_unity_webapi
    depends_on:
      redis:
        condition: service_healthy
      keycloak:
        condition: service_started
      identity_db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - REDIS_CONNECTION=redis:6379
      - KEYCLOAK_AUTH_URL=http://keycloak:8080/realms/core-unity/protocol/openid-connect/token
    ports:
      - "8080:8080"
    restart: always

  any-admin-front-end:
    container_name: any_admin_frontend
    build:
      context: ./any-admin-front-end
      dockerfile: Dockerfile
    ports:
      - "4000:80"
    depends_on:
      - coreunity.webapi

  nginx:
    image: nginx:latest
    container_name: reverse_proxy_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - any-admin-front-end
      - coreunity.webapi

volumes:
  redis_data:
  keycloak_db_data:
  keycloak_data:
  identity_db_data:
