services:
  coreunity.webapi:
    image: coreunitywebapi:dev
    build:
      args:
        LAUNCHING_FROM_VS: true
        BUILD_CONFIGURATION: Debug
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "CoreUnity.WebAPI"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=/.nuget/fallbackpackages;/.nuget/fallbackpackages2
    volumes:
      - C:\Users\csolis\Desktop\CSOLIS\Desarrollo\CESARSOFTNICA\PROJECTS\NicaSoft\CoreUnityProject\core-unity\CoreUnityBackend\CoreUnity.WebAPI:/app:rw
      - C:\Users\csolis\Desktop\CSOLIS\Desarrollo\CESARSOFTNICA\PROJECTS\NicaSoft\CoreUnityProject\core-unity\CoreUnityBackend:/src:rw
      - C:\Users\csolis\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\csolis\.nuget\packages:/.nuget/packages:ro
      - C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages:/.nuget/fallbackpackages:ro
      - C:\Program Files\DevExpress 22.2\Components\Offline Packages:/.nuget/fallbackpackages2:ro
      - C:\Users\csolis\AppData\Roaming\ASP.NET\Https:/root/.aspnet/https:ro
      - C:\Users\csolis\AppData\Roaming\ASP.NET\Https:/home/app/.aspnet/https:ro
      - C:\Users\csolis\AppData\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets:ro
      - C:\Users\csolis\AppData\Roaming\Microsoft\UserSecrets:/home/app/.microsoft/usersecrets:ro
      - C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Sdks\Microsoft.Docker.Sdk\tools\linux-x64\net8.0:/VSTools:ro
      - C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\HotReload:/HotReloadAgent:ro

    entrypoint: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --wait"
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /.nuget/packages --additionalProbingPath /.nuget/fallbackpackages --additionalProbingPath /.nuget/fallbackpackages2  \"/app/bin/Debug/net8.0/CoreUnity.WebAPI.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --stop dotnet"
    tty: true